# nginx reverse proxy for the TS3 Webinterface – generated by deploy/install.sh
# Placeholders: @SERVER_NAME@ @PORT@
# HTTPS: run  certbot --nginx -d @SERVER_NAME@  (package certbot / python3-certbot-nginx)
server {
    listen 80;
    listen [::]:80;
    server_name @SERVER_NAME@;

    # Large backup uploads
    client_max_body_size 4096m;

    location / {
        proxy_pass http://127.0.0.1:@PORT@;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";

        # Server-Sent Events (live feed) and long backup downloads
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }
}
