# systemd unit for the TS3 Webinterface – generated by deploy/install.sh
# Placeholders: @APP_DIR@ @APP_USER@ @SERVICE@ @NODE@
[Unit]
Description=TS3 Webinterface (TeamSpeak 3 server management)
Documentation=https://github.com/dinh1405/ts3-Webinterface
After=network.target

[Service]
Type=simple
User=@APP_USER@
Group=@APP_USER@
WorkingDirectory=@APP_DIR@
EnvironmentFile=@APP_DIR@/.env
Environment=NODE_ENV=production
ExecStart=@NODE@ server/index.js
Restart=always
RestartSec=5
TimeoutStopSec=20

# IMPORTANT for control mode "script": a ts3server started from the webinterface is a child
# process inside this unit's cgroup. KillMode=process makes "systemctl restart/stop @SERVICE@"
# end only the webinterface and NOT the TeamSpeak server.
KillMode=process

# Hardening. ProtectHome stays off because TeamSpeak servers often live under /home.
# No options that imply NoNewPrivileges (ProtectKernelTunables, ProtectControlGroups, RestrictSUIDSGID, …):
# they would break sudo (systemd/docker control modes) and setuid helpers such as sendmail wrappers.
PrivateTmp=true
ProtectSystem=full
ProtectHome=false

[Install]
WantedBy=multi-user.target
